/* TRACE_CON causal local TRACE_1M engine. It never sends orders or uses future candles. */
(() => {
  "use strict";
  const TF = "1m";
  const n = (value, fallback = 0) => Number.isFinite(Number(value)) ? Number(value) : fallback;
  const mean = (xs) => xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : 0;
  const ema = (xs, period) => { if (!xs.length) return []; const k = 2 / (period + 1); const out = [xs[0]]; for (let i = 1; i < xs.length; i++) out.push(xs[i] * k + out[i - 1] * (1 - k)); return out; };
  const stdev = (xs) => { const m = mean(xs); return Math.sqrt(mean(xs.map((x) => (x - m) ** 2))); };
  const bucket = (value, weak, strong, labels = ["WEAK", "NORMAL", "STRONG"]) => Math.abs(value) >= strong ? labels[2] : Math.abs(value) >= weak ? labels[1] : labels[0];
  const direction = (value) => value > 0 ? "UP" : value < 0 ? "DOWN" : "FLAT";
  const candlesOf = (item) => (item?.candles || []).filter((c) => c.timeframe === TF && c.isClosed !== false).map((c) => ({ ...c, open: n(c.open, n(c.close)), high: n(c.high, n(c.close)), low: n(c.low, n(c.close)), close: n(c.close), timestamp: n(c.timestamp) })).sort((a, b) => a.timestamp - b.timestamp);
  const aggregate = (candles, minutes) => {
    const size = minutes * 60_000; const groups = new Map();
    for (const c of candles) { const t = Math.floor(c.timestamp / size) * size; groups.set(t, [...(groups.get(t) || []), c]); }
    return [...groups.entries()].sort(([a], [b]) => a - b).map(([timestamp, group]) => ({ timestamp, open: group[0].open, close: group.at(-1).close, high: Math.max(...group.map((c) => c.high)), low: Math.min(...group.map((c) => c.low)) }));
  };
  const rsi = (closes, period = 14) => { if (closes.length <= period) return null; let gain = 0; let loss = 0; for (let i = closes.length - period; i < closes.length; i++) { const d = closes[i] - closes[i - 1]; gain += Math.max(0, d); loss += Math.max(0, -d); } return loss === 0 ? 100 : 100 - 100 / (1 + gain / loss); };
  const geometry = (c) => { const range = Math.max(c.high - c.low, Number.EPSILON); const body = Math.abs(c.close - c.open) / range; return { bodyRatio: body, upperWickRatio: (c.high - Math.max(c.open, c.close)) / range, lowerWickRatio: (Math.min(c.open, c.close) - c.low) / range, closeLocation: (c.close - c.low) / range, range }; };
  const tickFeatures = (ticks) => {
    const rows = (ticks || []).slice(-200).filter((t) => Number.isFinite(n(t.price)) && Number.isFinite(n(t.timestamp))).sort((a, b) => n(a.timestamp) - n(b.timestamp));
    if (rows.length < 2) return { available: false, tickCount: rows.length, upticks: 0, downticks: 0, imbalance: null, velocity: null, acceleration: null, directionChanges: null, intrabarRange: null, pathEfficiency: null };
    let up = 0; let down = 0; let changes = 0; let previous = 0; let path = 0;
    for (let i = 1; i < rows.length; i++) { const d = n(rows[i].price) - n(rows[i - 1].price); path += Math.abs(d); const sign = Math.sign(d); if (sign > 0) up++; if (sign < 0) down++; if (sign && previous && sign !== previous) changes++; if (sign) previous = sign; }
    const duration = Math.max(1, n(rows.at(-1).timestamp) - n(rows[0].timestamp)); const velocity = (n(rows.at(-1).price) - n(rows[0].price)) / duration; const half = Math.floor(rows.length / 2); const v1 = (n(rows[half].price) - n(rows[0].price)) / Math.max(1, n(rows[half].timestamp) - n(rows[0].timestamp)); const v2 = (n(rows.at(-1).price) - n(rows[half].price)) / Math.max(1, n(rows.at(-1).timestamp) - n(rows[half].timestamp)); const prices = rows.map((t) => n(t.price));
    return { available: true, tickCount: rows.length, upticks: up, downticks: down, imbalance: (up - down) / Math.max(1, up + down), velocity, acceleration: v2 - v1, directionChanges: changes, intrabarRange: Math.max(...prices) - Math.min(...prices), pathEfficiency: Math.abs(prices.at(-1) - prices[0]) / Math.max(path, Number.EPSILON) };
  };
  const wilson = () => null; // No local historical claim; experiment runner computes observed statistics.

  function classifyOutcome(decision, entryPrice, exitPrice) { const entry = n(entryPrice, NaN); const exit = n(exitPrice, NaN); if (!Number.isFinite(entry) || entry <= 0 || !Number.isFinite(exit)) return "UNKNOWN"; const signed = (exit - entry) / entry * (decision === "SELL" ? -1 : 1); return Math.abs(signed) < 0.00001 ? "DRAW" : signed > 0 ? "WIN" : "LOSS"; }

  function analyze(symbol, item) {
    const candles = candlesOf(item); const currentPrice = item?.lastPrice ?? candles.at(-1)?.close ?? null; const ageMs = item?.lastFrameAt ? Date.now() - item.lastFrameAt : Infinity; const base = { symbol, timeframe: TF, currentPrice, source: "iqoption:local-shadow", provider: "iqoption", feed: { state: ageMs <= 15_000 ? "LIVE" : "DEGRADED", lastPrice: currentPrice, lastPriceTimestamp: item?.lastPriceTimestamp ?? null, ageMs, candleCount: candles.length } };
    if (candles.length < 30) return { ...base, decision: "WAIT", confidence: 0, rationale: "IQ_DATA_INSUFFICIENT_HISTORY", productionDecision: "WAIT", shadowEligible: false, reasons: ["IQ_DATA_INSUFFICIENT_HISTORY"], counterReasons: ["INSUFFICIENT_CLOSED_CANDLES"], features: { availability: "PARTIAL", candles: candles.length }, signature: "WAIT|INSUFFICIENT_HISTORY", snapshot: { asset: symbol, timeframe: TF, observedAt: Date.now(), price: currentPrice, candles: candles.slice(-30).map((c) => ({ ...c })) } };
    if (ageMs > 15_000) return { ...base, decision: "WAIT", confidence: 0, rationale: "IQ_FEED_STALE", productionDecision: "WAIT", shadowEligible: false, reasons: ["IQ_FEED_STALE"], counterReasons: ["STALE_MARKET_FRAME"], features: { availability: "STALE", candles: candles.length }, signature: "WAIT|STALE_FEED", snapshot: { asset: symbol, timeframe: TF, observedAt: Date.now(), price: currentPrice, candles: candles.slice(-30).map((c) => ({ ...c })) } };
    const closes = candles.map((c) => c.close); const last = candles.at(-1); const prev = candles.at(-2); const returns = (window) => (last.close - closes.at(-1 - window)) / Math.max(Math.abs(closes.at(-1 - window)), Number.EPSILON); const r1 = returns(1), r5 = returns(5), r10 = returns(10), r20 = returns(20); const e8 = ema(closes, 8), e21 = ema(closes, 21); const emaSlope = (e8.at(-1) - e8.at(-6)) / Math.max(Math.abs(e8.at(-6)), Number.EPSILON); const mediumSlope = (e21.at(-1) - e21.at(-6)) / Math.max(Math.abs(e21.at(-6)), Number.EPSILON); const distanceEma = (last.close - e21.at(-1)) / Math.max(Math.abs(e21.at(-1)), Number.EPSILON);
    const trs = candles.slice(1).map((c, i) => Math.max(c.high - c.low, Math.abs(c.high - candles[i].close), Math.abs(c.low - candles[i].close))); const atr = mean(trs.slice(-14)); const ranges = candles.map((c) => c.high - c.low); const rangePct = ranges.filter((x) => x <= ranges.at(-1)).length / ranges.length; const rollingVol = stdev(closes.slice(-20).map((x, i, a) => i ? (x - a[i - 1]) / Math.max(Math.abs(a[i - 1]), Number.EPSILON) : 0)); const middle = mean(closes.slice(-20)); const bbWidth = 4 * stdev(closes.slice(-20)) / Math.max(Math.abs(middle), Number.EPSILON); const geom = geometry(last); const prevGeom = geometry(prev);
    const high20 = Math.max(...candles.slice(-20, -1).map((c) => c.high)), low20 = Math.min(...candles.slice(-20, -1).map((c) => c.low)); const breakoutUp = last.close > high20, breakoutDown = last.close < low20; const inside = last.high <= prev.high && last.low >= prev.low; const outside = last.high >= prev.high && last.low <= prev.low; const bullishEngulf = last.close > last.open && prev.close < prev.open && last.close >= prev.open && last.open <= prev.close; const bearishEngulf = last.close < last.open && prev.close > prev.open && last.open >= prev.close && last.close <= prev.open; const bullishReject = geom.lowerWickRatio > .45 && geom.closeLocation > .6; const bearishReject = geom.upperWickRatio > .45 && geom.closeLocation < .4;
    const swingHigh = Math.max(...candles.slice(-8).map((c) => c.high)), swingLow = Math.min(...candles.slice(-8).map((c) => c.low)); const structure = r10 > 0 && last.high >= swingHigh ? "HH_HL" : r10 < 0 && last.low <= swingLow ? "LH_LL" : "RANGE"; const equalHighs = Math.abs(last.high - prev.high) <= Math.max(atr * .1, Number.EPSILON); const equalLows = Math.abs(last.low - prev.low) <= Math.max(atr * .1, Number.EPSILON); const sweep = (last.high > high20 && last.close < high20) || (last.low < low20 && last.close > low20);
    const m5 = aggregate(candles, 5), m15 = aggregate(candles, 15); const d5 = m5.length >= 3 ? direction(m5.at(-1).close - m5.at(-3).close) : "UNAVAILABLE"; const d15 = m15.length >= 2 ? direction(m15.at(-1).close - m15[0].close) : "UNAVAILABLE"; const trendDir = direction(emaSlope + mediumSlope); const mtfAligned = (trendDir === "UP" && d5 === "UP" && d15 !== "DOWN") || (trendDir === "DOWN" && d5 === "DOWN" && d15 !== "UP");
    const ticks = tickFeatures(item?.ticks); const regime = rollingVol > .0018 ? "CHAOTIC" : bbWidth < .0008 ? "COMPRESSION" : (breakoutUp || breakoutDown) ? "BREAKOUT" : Math.abs(r10) > Math.max(atr / Math.max(last.close, Number.EPSILON) * 2, .0004) ? "TREND" : rangePct > .8 ? "EXPANSION" : "RANGE";
    const momentum = r5 + r10 + emaSlope; const directionModel = momentum > .00025 ? "BUY" : momentum < -.00025 ? "SELL" : "WAIT"; const contextPass = regime !== "CHAOTIC" && !inside && (directionModel === "BUY" ? (!bearishReject && (trendDir === "UP" || bullishReject)) : directionModel === "SELL" ? (!bullishReject && (trendDir === "DOWN" || bearishReject)) : false); const take = directionModel !== "WAIT" && contextPass && ageMs <= 15_000;
    const trendStrength = bucket(emaSlope + mediumSlope, .00015, .0006); const momentumBucket = bucket(momentum, .0002, .0008); const volatility = bbWidth < .0008 ? "LOW" : bbWidth > .003 ? "HIGH" : "NORMAL"; const signature = take ? [directionModel, regime, `TREND_${trendDir}_${trendStrength}`, `MOM_${momentumBucket}`, `VOL_${volatility}`, mtfAligned ? "MTF_ALIGNED" : "MTF_MIXED", structure, ticks.available ? (ticks.imbalance > .15 ? "TICK_UP" : ticks.imbalance < -.15 ? "TICK_DOWN" : "TICK_BALANCED") : "TICK_UNAVAILABLE"].join("|") : "WAIT|NO_TAKE";
    const confidence = Math.min(.79, .42 + Math.min(.16, Math.abs(momentum) * 80) + (mtfAligned ? .08 : 0) + (ticks.available && Math.abs(ticks.imbalance) > .15 ? .05 : 0)); const features = { candle: { ...geom, bullBear: last.close >= last.open ? "BULL" : "BEAR", consecutive: candles.slice(-5).every((c) => c.close >= c.open) ? "BULL_SEQUENCE" : candles.slice(-5).every((c) => c.close <= c.open) ? "BEAR_SEQUENCE" : "MIXED", inside, outside, bullishEngulf, bearishEngulf, bullishReject, bearishReject }, trend: { direction: trendDir, emaSlope, mediumSlope, distanceEma, strength: trendStrength, structure, hhHl: structure === "HH_HL", lhLl: structure === "LH_LL" }, momentum: { roc1: r1, roc5: r5, roc10: r10, roc20: r20, acceleration: r5 - r10 / 2, rsi: rsi(closes), stochastic: (last.close - Math.min(...candles.slice(-14).map((c) => c.low))) / Math.max(Math.max(...candles.slice(-14).map((c) => c.high)) - Math.min(...candles.slice(-14).map((c) => c.low)), Number.EPSILON) * 100 }, volatility: { atr, trueRange: trs.at(-1), rollingVolatility: rollingVol, rangePercentile: rangePct, bollingerWidth: bbWidth, compression: regime === "COMPRESSION", expansion: regime === "EXPANSION" }, priceAction: { breakoutUp, breakoutDown, failedBreakout: sweep, retest: false, impulse: geom.bodyRatio > .7, pullback: direction(r1) !== trendDir && trendDir !== "FLAT", exhaustionProxy: geom.bodyRatio < .2 && (bullishReject || bearishReject) }, structure: { swingHigh, swingLow, bos: breakoutUp || breakoutDown, choch: structure === "RANGE" && trendDir !== "FLAT", equalHighs, equalLows, liquiditySweepProxy: sweep, supportDistance: (last.close - swingLow) / Math.max(last.close, Number.EPSILON), resistanceDistance: (swingHigh - last.close) / Math.max(last.close, Number.EPSILON) }, mtf: { direction5m: d5, direction15m: d15, aligned: mtfAligned }, ticks, regime, directionModel, takeFilter: take };
    const reasons = take ? [`DIRECTION_${directionModel}`, `REGIME_${regime}`, `TREND_${trendDir}`, `MOMENTUM_${momentumBucket}`] : ["META_FILTER_WAIT", `REGIME_${regime}`]; const counterReasons = [!mtfAligned ? "MTF_NOT_ALIGNED" : null, ticks.available && ticks.directionChanges > 8 ? "TICK_REVERSAL_RISK" : null, regime === "CHAOTIC" ? "CHAOTIC_REGIME" : null].filter(Boolean);
    return { ...base, decision: take ? directionModel : "WAIT", directionModel, takeFilter: take, confidence: take ? confidence : 0, score: momentum, rationale: take ? "LOCAL_FEATURE_CONTEXT_SHADOW" : "LOCAL_META_FILTER_WAIT", productionDecision: "WAIT", shadowEligible: take, candlesUsed: 30, generatedAt: Date.now(), regime, features, reasons, counterReasons, signature, snapshot: { asset: symbol, timeframe: TF, observedAt: Date.now(), price: currentPrice, candles: candles.slice(-30).map((c) => ({ ...c })), ticks: (item?.ticks || []).slice(-200).map((t) => ({ ...t })) } };
  }
  globalThis.TraceConLocalEngine = { analyze, classifyOutcome, aggregate, tickFeatures, version: "trace1m-local-v2" };
})();
