import { calibratePlatt, CALIBRATION_VERSION } from "./calibration.js";
import { classifyRegime, REGIME_VERSION } from "./regime-engine.js";
import { baselineModel, MODEL_VERSION } from "./models.js";
import { findSimilarPatterns, type HistoricalPattern } from "./similar-pattern.js";
import type { FeatureSnapshot, QuantDecision, SimilarPatternResult } from "./types.js";

export const POLICY_VERSION = "quant-v2-shadow-policy-v1";
export function quantShadowDecision(input: { snapshot: FeatureSnapshot; history?: HistoricalPattern[]; labels?: number[]; now?: number }): QuantDecision {
  const supervised = baselineModel(input.snapshot.features); const similar: SimilarPatternResult = findSimilarPatterns(input.snapshot, input.history ?? [], { k: 30 }); const neighborhood = { pUp: similar.pUpNeighborhood, pDown: similar.pDownNeighborhood, pNoEdge: similar.neighborCount ? similar.drawCount / similar.neighborCount : null, confidence: similar.confidenceFromNeighborhood, version: "quant-v2-knn-cosine-v1", sampleSize: similar.neighborCount };
  const raw = supervised.pUp ?? .5; const cal = calibratePlatt(raw, input.labels ?? []); const pUp = ((supervised.pUp ?? .5) + (neighborhood.pUp ?? .5)) / 2, pDown = ((supervised.pDown ?? .5) + (neighborhood.pDown ?? .5)) / 2, pNoEdge = Math.max(supervised.pNoEdge ?? 0, neighborhood.pNoEdge ?? 0); const edge = Math.max(pUp, pDown) - pNoEdge; const direction = edge < .12 ? "NO_EDGE" : pUp > pDown ? "BUY" : "SELL";
  const regime = classifyRegime(input.snapshot.features); const disagreement = Math.abs((supervised.pUp ?? .5) - (neighborhood.pUp ?? .5)) > .25 ? ["supervised_vs_neighborhood"] : []; return { quantDecisionId: `qdec_${input.snapshot.timestamp}`, decisionTimestamp: input.now ?? input.snapshot.timestamp, direction, pUp, pDown, pNoEdge, calibratedConfidence: cal.calibrated, regime, components: { supervised, neighborhood, online: { pUp: null, pDown: null, pNoEdge: null, confidence: null, version: "river-unavailable-shadow", sampleSize: 0 }, regime: { pUp: regime.regime === "TREND_UP" ? .7 : null, pDown: regime.regime === "TREND_DOWN" ? .7 : null, pNoEdge: regime.regime === "RANGE" ? .7 : null, confidence: regime.confidence, version: REGIME_VERSION, sampleSize: 1 } }, disagreement, reasons: ["shadow_only", `regime=${regime.regime}`, `calibration=${CALIBRATION_VERSION}`], featureVersion: input.snapshot.featureVersion, modelVersion: MODEL_VERSION, calibrationVersion: CALIBRATION_VERSION, regimeVersion: REGIME_VERSION, policyVersion: POLICY_VERSION, shadowOnly: true };
}
