import { createHash } from "node:crypto";

export const sha256 = (data) => createHash("sha256").update(data).digest("hex");
export const mean = (xs) => xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : null;
export const variance = (xs) => { const m = mean(xs); return m == null ? null : mean(xs.map((x) => (x - m) ** 2)); };
export const quantile = (xs, p) => { if (!xs.length) return null; const a = [...xs].sort((x, y) => x - y); return a[Math.min(a.length - 1, Math.floor((a.length - 1) * p))]; };
export const normalizeCandles = (payload) => (payload.candles ?? []).map((c) => ({ at: Date.parse(c.to), from: Date.parse(c.from), open: Number(c.open), high: Number(c.max ?? c.high), low: Number(c.min ?? c.low), close: Number(c.close), raw: c })).filter((c) => Number.isFinite(c.at) && [c.open, c.high, c.low, c.close].every(Number.isFinite)).sort((a, b) => a.at - b.at);
export function audit(candles, sourceBytes, expectedMs = 60_000) {
  const diffs = candles.slice(1).map((c, i) => c.at - candles[i].at); const uniqueTimes = new Set(candles.map((c) => c.at));
  const gaps = diffs.filter((d) => d > expectedMs).map((d) => ({ seconds: d / 1000, missingCandles: Math.max(0, Math.round(d / expectedMs) - 1) }));
  const decimals = candles.map((c) => { const s = String(c.close); return (s.split(".")[1] ?? "").length; });
  const prices = candles.map((c) => Math.round(c.close * 1e8)); const increments = prices.slice(1).map((p, i) => Math.abs(p - prices[i])).filter(Boolean);
  const gcd = (a, b) => b ? gcd(b, a % b) : a; const quantumUnits = increments.reduce((a, b) => gcd(a, b), increments[0] ?? 0);
  const lastDigitCounts = Array(10).fill(0); for (const c of candles) lastDigitCounts[Math.abs(Math.round(c.close * 1e6)) % 10]++;
  return { sourceSha256: sha256(sourceBytes), sourceBytes: sourceBytes.length, product: "blitz", assetId: 76, asset: "EUR/USD (OTC)", candleCount: candles.length, intervalSeconds: expectedMs / 1000, from: candles[0] ? new Date(candles[0].at).toISOString() : null, to: candles.at(-1) ? new Date(candles.at(-1).at).toISOString() : null, elapsedHours: candles.length > 1 ? (candles.at(-1).at - candles[0].at) / 3.6e6 : 0, duplicateTimestamps: candles.length - uniqueTimes.size, gapCount: gaps.length, gaps, expectedStepContinuityPct: diffs.length ? diffs.filter((d) => d === expectedMs).length / diffs.length * 100 : null, minimumDecimalPlaces: Math.min(...decimals), maximumDecimalPlaces: Math.max(...decimals), smallestNonzeroCloseIncrement: increments.length ? Math.min(...increments) / 1e8 : null, gcdCloseIncrement: quantumUnits / 1e8, closeLastDigitCountsAt6Decimals: lastDigitCounts, payoutObserved: null, payoutNote: "not present in historical candle payload", effectiveIndependent300sUpperBound: Math.floor((candles.at(-1)?.at - candles[0]?.at) / 300_000) };
}
export function candleSeries(candles) { return candles.map((c, i) => { const prev = candles[i - 1]?.close; const contiguous = i > 0 && c.at - candles[i - 1].at === 60_000; const ret = contiguous && prev ? c.close / prev - 1 : null; return { timestamp: new Date(c.at).toISOString(), open: c.open, high: c.high, low: c.low, close: c.close, return: ret, logReturn: ret == null ? null : Math.log(c.close / prev), direction: ret == null ? null : ret > 0 ? "UP" : ret < 0 ? "DOWN" : "FLAT", range: c.high - c.low, body: c.close - c.open, upperWick: c.high - Math.max(c.open, c.close), lowerWick: Math.min(c.open, c.close) - c.low, volatility: ret == null ? null : Math.abs(ret) }; }); }
export function horizonReturns(candles, seconds) { const ms = seconds * 1000; if (seconds < 60) return { horizonSeconds: seconds, available: false, reason: "1m candles cannot resolve this horizon" }; const result = []; for (let i = 0; i < candles.length; i++) { let j = i + 1; while (j < candles.length && candles[j].at < candles[i].at + ms) j++; if (j >= candles.length || candles[j].at - candles[i].at !== ms) continue; const r = candles[j].close / candles[i].close - 1; result.push(r); } const avg = mean(result); const v = variance(result); const centered = result.map((x) => x - avg); const skew = v ? mean(centered.map((x) => x ** 3)) / v ** 1.5 : null; const kurtosis = v ? mean(centered.map((x) => x ** 4)) / (v ** 2) - 3 : null; return { horizonSeconds: seconds, available: true, nOverlapping: result.length, mean: avg, sd: v == null ? null : Math.sqrt(v), skewness: skew, excessKurtosis: kurtosis, quantiles: Object.fromEntries([0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99].map((p) => [p, quantile(result, p)])), upPct: result.filter((x) => x > 0).length / (result.length || 1), independentStrideN: Math.floor(result.length / (seconds / 60)) };
}
export function acf(xs, maxLag = 30) { const m = mean(xs); const den = xs.reduce((s, x) => s + (x - m) ** 2, 0); return Array.from({ length: Math.min(maxLag, xs.length - 2) }, (_, k) => { const lag = k + 1; let n = 0; for (let i = lag; i < xs.length; i++) n += (xs[i] - m) * (xs[i - lag] - m); const value = den ? n / den : null; return { lag, value, approximate95Upper: 1.96 / Math.sqrt(xs.length), bonferroni30Upper: 3.15 / Math.sqrt(xs.length), significantUncorrected: Math.abs(value ?? 0) > 1.96 / Math.sqrt(xs.length), significantBonferroniApprox: Math.abs(value ?? 0) > 3.15 / Math.sqrt(xs.length) }; }); }
export function periodogram(xs, cadenceSeconds = 60, minPeriodSeconds = 60, maxPeriodSeconds = 1800) { const m = mean(xs); const centered = xs.map((x) => x - m); const n = centered.length; const rows = []; for (let period = minPeriodSeconds; period <= maxPeriodSeconds; period += cadenceSeconds) { const omega = 2 * Math.PI * cadenceSeconds / period; let re = 0, im = 0; for (let i = 0; i < n; i++) { re += centered[i] * Math.cos(omega * i); im += centered[i] * Math.sin(omega * i); } rows.push({ periodSeconds: period, power: (re * re + im * im) / Math.max(1, n) }); } return rows.sort((a, b) => b.power - a.power); }
export function motifNearest(candles, durationsMinutes = [.5, 1, 2, 5, 10, 15]) { const out = []; for (const w of durationsMinutes) { if (w < 3) { out.push({ durationMinutes: w, status: w * 60 < 60 ? "BELOW_RESOLUTION" : "TOO_SHORT_TO_NORMALIZE" }); continue; } if (candles.length < 2 * w + 10) { out.push({ durationMinutes: w, status: "INSUFFICIENT_SAMPLE" }); continue; } const ret = candles.slice(1).map((c, i) => Math.log(c.close / candles[i].close)); const rows = []; for (let i = 2 * w + 5; i < candles.length - 5; i += 1) { const q = ret.slice(i - w, i); const qm = mean(q), qs = Math.sqrt(variance(q)) || 1; let best = null; for (let j = w; j <= i - 2 * w - 5; j += 1) { const r = ret.slice(j - w, j); const rm = mean(r), rs = Math.sqrt(variance(r)) || 1; let d = 0; for (let k = 0; k < w; k++) d += ((q[k] - qm) / qs - (r[k] - rm) / rs) ** 2; d = Math.sqrt(d / w); if (!best || d < best.distance) best = { j, distance: d }; } if (!best) continue; const refSide = candles[best.j + 5].close > candles[best.j].close ? "UP" : "DOWN"; const actual = candles[i + 5].close > candles[i].close ? "UP" : "DOWN"; rows.push({ distance: best.distance, correct: refSide === actual }); } out.push({ durationMinutes: w, status: "EXPLORATORY_NONOVERLAPPING_NEAREST", queryCount: rows.length, medianNormalizedDistance: quantile(rows.map((x) => x.distance), .5), next300sAccuracy: rows.length ? rows.filter((x) => x.correct).length / rows.length : null, independentUpperBound: Math.floor(rows.length / 5), caution: "Nearest neighbor search reuses history across queries; accuracy is descriptive and requires untouched future validation." }); } return out; }
export function makeForecastSamples(candles) { const out = []; for (let i = 30; i < candles.length - 5; i += 5) { const w = candles.slice(i - 20, i + 1); if (w.some((c, k) => k && c.at - w[k - 1].at !== 60_000) || candles[i + 5].at - candles[i].at !== 300_000) continue; const rs = w.slice(1).map((c, k) => Math.log(c.close / w[k].close)); const current = w.at(-1); const range = current.high - current.low; const xs = [rs.at(-1), rs.at(-2), rs.at(-3), rs.slice(-5).reduce((a,b)=>a+b,0), rs.slice(-10).reduce((a,b)=>a+b,0), mean(rs.slice(-5).map(Math.abs)), mean(rs.slice(-20).map(Math.abs)), current.close ? (current.close-current.open)/current.close : 0, current.close ? range/current.close : 0]; out.push({ at: current.at, x: xs, y: candles[i + 5].close > current.close ? 1 : candles[i + 5].close < current.close ? 0 : null }); } return out.filter((r) => r.y !== null); }
export function fitLogistic(samples) { const n = samples.length, p = samples[0]?.x.length ?? 0; const mu = Array.from({length:p},(_,j)=>mean(samples.map(r=>r.x[j]))); const sd = Array.from({length:p},(_,j)=>Math.sqrt(variance(samples.map(r=>r.x[j])) ?? 0) || 1); let b=0,w=Array(p).fill(0); const sigmoid=(z)=>1/(1+Math.exp(-Math.max(-30,Math.min(30,z)))); for(let iter=0;iter<1500;iter++){let gb=0,gw=Array(p).fill(0);for(const r of samples){const x=r.x.map((v,j)=>(v-mu[j])/sd[j]);const e=sigmoid(b+x.reduce((s,v,j)=>s+v*w[j],0))-r.y;gb+=e;for(let j=0;j<p;j++)gw[j]+=e*x[j];}const rate=.08/Math.sqrt(1+iter/100);b-=rate*gb/n;for(let j=0;j<p;j++)w[j]-=rate*(gw[j]/n+.01*w[j]);}return {predict:(x)=>sigmoid(b+x.reduce((s,v,j)=>s+((v-mu[j])/sd[j])*w[j],0)),coefficients:w,intercept:b};}
export function forecastMetrics(rows) { if (!rows.length) return { n:0 }; const ys=rows.map(r=>r.y), ps=rows.map(r=>r.p), wins=rows.filter(r=>(r.p>=.5?1:0)===r.y).length; const up=rows.filter(r=>r.y===1),dn=rows.filter(r=>r.y===0); const sorted=rows.map(r=>r.p).sort((a,b)=>a-b); let pairs=0,good=0;for(const a of up)for(const b of dn){pairs++;if(a.p>b.p)good++;else if(a.p===b.p)good+=.5;} const coverage=[1,.5,.25,.1,.05,.01].map(f=>{const n=Math.max(1,Math.ceil(rows.length*f));const chosen=[...rows].sort((a,b)=>Math.abs(b.p-.5)-Math.abs(a.p-.5)).slice(0,n);return {coverage:f,n,accuracy:chosen.filter(r=>(r.p>=.5?1:0)===r.y).length/n,meanConfidence:mean(chosen.map(r=>Math.max(r.p,1-r.p)))};}); const calibration=Array.from({length:5},(_,i)=>{const a=rows.filter(r=>r.p>=i/5&&r.p<(i+1)/5+(i===4?1e-9:0));return {bin:`${i/5}-${(i+1)/5}`,n:a.length,meanP:mean(a.map(r=>r.p)),observedUp:a.length?mean(a.map(r=>r.y)):null};}); return {n:rows.length,accuracy:wins/rows.length,balancedAccuracy:((up.length?up.filter(r=>r.p>=.5).length/up.length:0)+(dn.length?dn.filter(r=>r.p<.5).length/dn.length:0))/2,auc:pairs?good/pairs:null,brier:mean(rows.map(r=>(r.p-r.y)**2)),logLoss:mean(rows.map(r=>-r.y*Math.log(Math.max(1e-12,r.p))-(1-r.y)*Math.log(Math.max(1e-12,1-r.p)))),coverage,calibration,baseRates:{up:up.length/rows.length,down:dn.length/rows.length}}; }
export function fitGaussianHMM(xs, k = 2, iterations = 40) { const values=xs.filter(Number.isFinite); const n=values.length; if(n<k*20) throw new Error("HMM_SAMPLE_TOO_SMALL"); const sorted=[...values].sort((a,b)=>a-b); const overall=mean(values), baseVar=variance(values)||1e-12; let mu=Array.from({length:k},(_,s)=>sorted[Math.floor((s+.5)*n/k)]); let vv=Array(k).fill(baseVar), A=Array.from({length:k},(_,i)=>Array.from({length:k},(_,j)=>i===j?.9:.1/(k-1))), pi=Array(k).fill(1/k); const pdf=(x,m,v)=>Math.exp(-.5*(x-m)**2/Math.max(v,1e-18))/Math.sqrt(2*Math.PI*Math.max(v,1e-18)); let ll=0,gamma;
  for(let iter=0;iter<iterations;iter++){const e=values.map(x=>mu.map((m,s)=>pdf(x,m,vv[s])));const alpha=Array.from({length:n},()=>Array(k).fill(0)),scale=Array(n).fill(1);for(let s=0;s<k;s++)alpha[0][s]=pi[s]*e[0][s];scale[0]=alpha[0].reduce((a,b)=>a+b,0)||1e-300;for(let s=0;s<k;s++)alpha[0][s]/=scale[0];for(let t=1;t<n;t++){for(let j=0;j<k;j++){let z=0;for(let i=0;i<k;i++)z+=alpha[t-1][i]*A[i][j];alpha[t][j]=z*e[t][j];}scale[t]=alpha[t].reduce((a,b)=>a+b,0)||1e-300;for(let j=0;j<k;j++)alpha[t][j]/=scale[t];}const beta=Array.from({length:n},()=>Array(k).fill(1));for(let t=n-2;t>=0;t--)for(let i=0;i<k;i++){let z=0;for(let j=0;j<k;j++)z+=A[i][j]*e[t+1][j]*beta[t+1][j];beta[t][i]=z/scale[t+1];}gamma=Array.from({length:n},(_,t)=>{const g=alpha[t].map((x,s)=>x*beta[t][s]);const z=g.reduce((a,b)=>a+b,0)||1;return g.map(x=>x/z);});const trans=Array.from({length:k},()=>Array(k).fill(0)),den=Array(k).fill(0);for(let t=0;t<n-1;t++){let z=0;const xi=Array.from({length:k},(_,i)=>Array.from({length:k},(_,j)=>alpha[t][i]*A[i][j]*e[t+1][j]*beta[t+1][j]));for(const row of xi)for(const x of row)z+=x;for(let i=0;i<k;i++){den[i]+=gamma[t][i];for(let j=0;j<k;j++)trans[i][j]+=xi[i][j]/(z||1);}}pi=gamma[0];A=trans.map((r,i)=>{const z=r.reduce((a,b)=>a+b,0)||1;return r.map(x=>x/z)});mu=Array.from({length:k},(_,s)=>values.reduce((z,x,t)=>z+gamma[t][s]*x,0)/(gamma.reduce((z,g)=>z+g[s],0)||1));vv=Array.from({length:k},(_,s)=>values.reduce((z,x,t)=>z+gamma[t][s]*(x-mu[s])**2,0)/(gamma.reduce((z,g)=>z+g[s],0)||1));ll=scale.reduce((z,x)=>z+Math.log(x),0); }
  const occ=Array.from({length:k},(_,s)=>gamma.reduce((z,g)=>z+g[s],0)/n);const params=k*k+2*k-1;return {states:k,means:mu,standardDeviations:vv.map(Math.sqrt),transition:A,initial:pi,occupancy:occ,meanDurationSteps:A.map((r,i)=>1/Math.max(1e-9,1-r[i])),logLikelihood:ll,bic:params*Math.log(n)-2*ll,iterations}; }
export function normalCdf(x) { const z=Math.abs(x)/Math.sqrt(2); const t=1/(1+.3275911*z); const erf=1-(((((1.061405429*t-1.453152027)*t)+1.421413741)*t-.284496736)*t+.254829592)*t*Math.exp(-z*z);return .5*(1+Math.sign(x)*erf); }
export function hmmForecastRows(candles, samples, model) { const k=model.states,mu=model.means,vv=model.standardDeviations.map(x=>x*x),A=model.transition;const rets=candles.slice(1).map((c,i)=>Math.log(c.close/candles[i].close));const pdf=(x,m,v)=>Math.exp(-.5*(x-m)**2/Math.max(v,1e-18))/Math.sqrt(2*Math.PI*Math.max(v,1e-18));const out=[];for(const r of samples){let ci=candles.findIndex(c=>c.at===r.at);if(ci<1||ci>=candles.length-5||candles[ci+5].at-candles[ci].at!==300_000)continue;let a=Array(k).fill(1/k);for(let t=0;t<ci;t++){const x=rets[t];const b=Array(k).fill(0);for(let j=0;j<k;j++)for(let i=0;i<k;i++)b[j]+=a[i]*A[i][j];for(let j=0;j<k;j++)b[j]*=pdf(x,mu[j],vv[j]);const z=b.reduce((s,x)=>s+x,0)||1e-300;a=b.map(x=>x/z);}let sm=0,sv=0;for(let h=0;h<5;h++){const b=Array(k).fill(0);for(let j=0;j<k;j++)for(let i=0;i<k;i++)b[j]+=a[i]*A[i][j];const m=b.reduce((s,p,j)=>s+p*mu[j],0);const v=b.reduce((s,p,j)=>s+p*(vv[j]+mu[j]**2),0)-m*m;sm+=m;sv+=v;a=b;}out.push({...r,p:normalCdf(sm/Math.sqrt(Math.max(1e-18,sv)))});}return out; }
export function directions300(candles) { const out = []; for (let i = 0; i < candles.length; i += 5) { const j = i + 5; if (!candles[j] || candles[j].at - candles[i].at !== 300_000) continue; out.push({ at: candles[i].at, direction: candles[j].close > candles[i].close ? "UP" : candles[j].close < candles[i].close ? "DOWN" : "FLAT", delta: candles[j].close - candles[i].close }); } return out; }
export function sequenceStats(dirs) { const seq = dirs.map((x) => x.direction).filter((x) => x !== "FLAT"); const counts = { UP: 0, DOWN: 0 }; for (const x of seq) counts[x]++; const trans = { UP_UP: 0, UP_DOWN: 0, DOWN_UP: 0, DOWN_DOWN: 0 }; for (let i = 1; i < seq.length; i++) trans[`${seq[i - 1]}_${seq[i]}`]++; const runs = []; for (const x of seq) { if (!runs.length || runs.at(-1).direction !== x) runs.push({ direction: x, length: 1 }); else runs.at(-1).length++; } const n = seq.length, n1 = counts.UP, n2 = counts.DOWN; const expectedRuns = 1 + 2 * n1 * n2 / Math.max(1, n); const runVar = n ? (2 * n1 * n2 * (2 * n1 * n2 - n)) / (n ** 2 * Math.max(1, n - 1)) : 0; const z = runVar > 0 ? (runs.length - expectedRuns) / Math.sqrt(runVar) : null; return { n, counts, transitions: trans, continuationPct: (trans.UP_UP + trans.DOWN_DOWN) / Math.max(1, n - 1), runCount: runs.length, meanRun: mean(runs.map((r) => r.length)), maxRun: Math.max(0, ...runs.map((r) => r.length)), runsTestZ: z, approximateTwoSidedP: z == null ? null : 2 * (1-normalCdf(Math.abs(z))), entropyBits: -Object.values(counts).reduce((s, c) => c ? s + c / n * Math.log2(c / n) : s, 0) };
}
export function markovOrders(dirs, maxOrder = 10) { const seq = dirs.map((x) => x.direction).filter((x) => x !== "FLAT"); const trainEnd = Math.floor(seq.length * 0.6), testStart = Math.floor(seq.length * 0.8); const train = seq.slice(0, trainEnd), test = seq.slice(testStart); const rows = []; const marginalH=(()=>{const p=test.filter(x=>x==="UP").length/Math.max(1,test.length);return -(p? p*Math.log2(p):0)-((1-p)?(1-p)*Math.log2(1-p):0)})(); for (let order = 0; order <= maxOrder; order++) { const map = new Map(); for (let i = order; i < train.length; i++) { const key = train.slice(i - order, i).join(""); const counts = map.get(key) ?? { UP: 0, DOWN: 0 }; counts[train[i]]++; map.set(key, counts); } let correct = 0, scored = 0; const testContexts=new Map(); for (let i = order; i < test.length; i++) { const key=test.slice(i-order,i).join("");const y=test[i];const tc=testContexts.get(key)??{UP:0,DOWN:0};tc[y]++;testContexts.set(key,tc);const c = map.get(key); if (!c || c.UP + c.DOWN < 10) continue; scored++; if ((c.UP >= c.DOWN ? "UP" : "DOWN") === y) correct++; } let conditionalH=0,den=0;for(const c of testContexts.values()){const n=c.UP+c.DOWN;const p=c.UP/n;conditionalH+=n*(-(p?p*Math.log2(p):0)-((1-p)?(1-p)*Math.log2(1-p):0));den+=n;}conditionalH=den?conditionalH/den:null;rows.push({ order, contexts: map.size, testPredictions: scored, correct, accuracy: scored ? correct / scored : null, testConditionalEntropyBits:conditionalH, estimatedInformationGainBits:conditionalH==null?null:marginalH-conditionalH, minimumContextCount: 10 }); } return { split: "first60_train_middle20_validation_last20_test; exploratory only, period previously inspected", trainN: train.length, testN: test.length, marginalTestEntropyBits:marginalH, rows }; }
export function permutationEntropy(xs, order = 3, delay = 1) { const counts=new Map();let n=0;for(let i=0;i+(order-1)*delay<xs.length;i++){const a=Array.from({length:order},(_,j)=>({v:xs[i+j*delay],j})).sort((x,y)=>x.v-y.v||x.j-y.j).map(x=>x.j).join("");counts.set(a,(counts.get(a)??0)+1);n++;}const h=-[...counts.values()].reduce((s,c)=>{const p=c/n;return s+p*Math.log2(p)},0);return{order,delay,n,patterns:counts.size,maxPatterns:factorial(order),entropyBits:h,normalizedEntropy:h/Math.log2(factorial(order))};}
const factorial=(n)=>n<2?1:n*factorial(n-1);
export function volatilityExpansionSignal(candles, i) { if (i < 20) return null; const w = candles.slice(i - 19, i + 1); if (w.some((x, k) => k && x.at - w[k - 1].at !== 60_000) || candles[i].at - candles[i - 5].at !== 300_000) return null; const closes = w.map((x) => x.close); const m = mean(closes); const st = Math.sqrt(variance(closes)); const width = m ? 2 * st / m : 0; const ret5m = candles[i].close / candles[i - 5].close - 1; return width > 0.003 ? (ret5m > 0 ? "UP" : ret5m < 0 ? "DOWN" : null) : null; }
export function testLookahead(candles, featureFn) { for (let i = 20; i < candles.length - 2; i++) { const before = featureFn(candles, i); const altered = candles.map((c, j) => j > i ? { ...c, close: c.close * (1 + (j % 2 ? 0.1 : -0.1)), high: c.high * 1.1, low: c.low * 0.9 } : c); const after = featureFn(altered, i); if (JSON.stringify(before) !== JSON.stringify(after)) return { passed: false, index: i }; } return { passed: true, checked: Math.max(0, candles.length - 22) }; }
