export const EXPERIMENT_ASSET = "USD/CAD (OTC)";
export type MarketContextStatus = "VALID" | "ASSET_MISMATCH" | "MARKET_TYPE_MISMATCH" | "TIMEFRAME_MISMATCH" | "VISIBLE_WINDOW_MISMATCH" | "EXPIRATION_MISMATCH" | "INSUFFICIENT_EVIDENCE";
export type MarketContext = { marketContextId: string; sessionId: string; segmentId: string; assetCanonical: string | null; assetDisplay: string | null; baseCurrency: string | null; quoteCurrency: string | null; marketType: "OTC" | "REAL_MARKET" | "UNKNOWN"; baseTimeframeSeconds: number | null; visibleWindowSeconds: number | null; tradeExpirationSeconds: number | null; source: string; frameId: string | null; observedAt: number; confidence: number; validationStatus: MarketContextStatus; createdAt: number };

function normalizeAsset(value: unknown): string | null { if (typeof value !== "string") return null; const text = value.toUpperCase().replace(/\s+/g, " ").trim(); if (/USD\s*\/\s*CAD\s*(\(\s*OTC\s*\)|OTC)/.test(text) || text === "USDCAD OTC") return EXPERIMENT_ASSET; if (/USD\s*\/\s*CAD|USDCAD/.test(text)) return null; return text || null; }
export function validateExperimentMarketContext(input: { sessionId: string; segmentId: string; asset?: unknown; marketType?: unknown; timeframeSeconds?: unknown; visibleWindowSeconds?: unknown; tradeExpirationSeconds?: unknown; frameId?: string | null; source?: string; confidence?: number; observedAt?: number }): MarketContext {
  const assetCanonical = normalizeAsset(input.asset); const marketType = String(input.marketType || "UNKNOWN").toUpperCase() === "OTC" ? "OTC" : String(input.marketType || "").toUpperCase() === "REAL_MARKET" ? "REAL_MARKET" : "UNKNOWN"; const timeframe = Number(input.timeframeSeconds); const visible = Number(input.visibleWindowSeconds); const expiration = Number(input.tradeExpirationSeconds); let validationStatus: MarketContextStatus = "VALID"; if (!assetCanonical) validationStatus = "INSUFFICIENT_EVIDENCE"; else if (assetCanonical !== EXPERIMENT_ASSET) validationStatus = "ASSET_MISMATCH"; else if (marketType !== "OTC") validationStatus = "MARKET_TYPE_MISMATCH"; else if (timeframe !== 5) validationStatus = "TIMEFRAME_MISMATCH"; else if (visible !== 300) validationStatus = "VISIBLE_WINDOW_MISMATCH"; else if (expiration !== 60) validationStatus = "EXPIRATION_MISMATCH";
  return { marketContextId: `mc_${input.observedAt || Date.now()}_${Math.random().toString(36).slice(2, 8)}`, sessionId: input.sessionId, segmentId: input.segmentId, assetCanonical, assetDisplay: typeof input.asset === "string" ? input.asset : null, baseCurrency: assetCanonical ? "USD" : null, quoteCurrency: assetCanonical ? "CAD" : null, marketType, baseTimeframeSeconds: Number.isFinite(timeframe) ? timeframe : null, visibleWindowSeconds: Number.isFinite(visible) ? visible : null, tradeExpirationSeconds: Number.isFinite(expiration) ? expiration : null, source: input.source || "VISION_CONTEXT", frameId: input.frameId || null, observedAt: input.observedAt || Date.now(), confidence: Number.isFinite(input.confidence) ? Math.max(0, Math.min(1, input.confidence!)) : 0, validationStatus, createdAt: Date.now() };
}

export function isEligibleForUsdCadOtcExperiment(context: MarketContext | null): boolean { return Boolean(context && context.validationStatus === "VALID" && context.assetCanonical === EXPERIMENT_ASSET && context.marketType === "OTC" && context.baseTimeframeSeconds === 5 && context.visibleWindowSeconds === 300 && context.tradeExpirationSeconds === 60); }
