CREATE TABLE IF NOT EXISTS trace_spans(id bigserial PRIMARY KEY,span_id text UNIQUE,parent_span_id text,trace_id text NOT NULL,session_id text,component text,operation text,started_at timestamptz,completed_at timestamptz,latency_ms integer,status text,error_code text,related_ids jsonb DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS trace_spans_trace_idx ON trace_spans(trace_id);
CREATE TABLE IF NOT EXISTS network_hops(id bigserial PRIMARY KEY,request_id text,trace_id text,hop text,route text,method text,status integer,started_at timestamptz,completed_at timestamptz,latency_ms integer,upstream text,error_code text,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS network_hops_trace_idx ON network_hops(trace_id);
CREATE TABLE IF NOT EXISTS decision_provenance(id bigserial PRIMARY KEY,decision_id text UNIQUE,session_id text,market_event_id text,frame_id text,candle_id text,price_observation_ids jsonb,context_versions jsonb,agent_run_ids jsonb,bull_run_id text,bear_run_id text,fusion_run_id text,arbiter_run_id text,profile text,threshold_version text,config_version text,prompt_version text,model_versions jsonb,raw_scores jsonb,calibrated_scores jsonb,decision text,directional_lean text,why jsonb,conflicts jsonb,warnings jsonb,trace_id text,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS decision_provenance_session_idx ON decision_provenance(session_id,created_at DESC);
CREATE TABLE IF NOT EXISTS state_transitions(id bigserial PRIMARY KEY,session_id text,machine text,from_state text,to_state text,reason text,signal_id text,market_event_id text,trace_id text,transitioned_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS state_transitions_session_idx ON state_transitions(session_id,transitioned_at DESC);
CREATE TABLE IF NOT EXISTS shadow_jobs(id bigserial PRIMARY KEY,job_id text UNIQUE,status text NOT NULL,requested_count integer,processed_count integer DEFAULT 0,failed_count integer DEFAULT 0,queue_depth integer DEFAULT 0,concurrency integer,idempotency_key text,created_at timestamptz NOT NULL DEFAULT now(),started_at timestamptz,completed_at timestamptz,result jsonb);
