-- 050: V2 LIVE (Strategy Core = rsi-skills-v2 ORIGINAL) sobre a infraestrutura/scheduler atuais.
-- Tabelas próprias para não misturar métricas com a V4. Registry/MESAS continuam compartilhados
-- (iq_rsi_instruments). Nunca persiste segredos.
CREATE TABLE IF NOT EXISTS iq_rsi_agent_state_v2live (
  agent_id text PRIMARY KEY,
  market_key text NOT NULL,
  instrument_type text NOT NULL DEFAULT 'BINARY',
  duration_seconds integer,
  strategy text NOT NULL,
  status text,
  decision text,
  wait_reason text,
  candidate_at bigint,
  candidate_age_ms bigint,
  candidate_rsi numeric,
  candidate_price numeric,
  revalidation_at bigint,
  submit_at bigint,
  expiry_at bigint,
  entry_mode text,
  rsi numeric,
  rsi_trajectory text,
  rsi_band text,
  bollinger jsonb,
  band jsonb,
  dmi jsonb,
  adx jsonb,
  expected_cushion numeric,
  cushion_class text,
  counter_evidence jsonb NOT NULL DEFAULT '[]'::jsonb,
  entry_reason jsonb NOT NULL DEFAULT '[]'::jsonb,
  order_id text,
  execution_id text,
  requested_stake numeric,
  effective_stake numeric,
  last_result text,
  last_pnl numeric,
  quality_class text,
  last_reason text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  watch_mode text,
  watch_started_at timestamptz,
  priority_started_at timestamptz,
  evaluation_count integer,
  last_evaluation_at timestamptz,
  evaluation_gap_ms integer,
  max_evaluation_gap_ms integer,
  time_to_expiry_ms integer,
  time_to_cutoff_ms integer,
  final_evaluation_at timestamptz,
  final_evaluation_lead_ms integer,
  submit_latency_ms integer,
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS iq_rsi_opportunities_v2live (
  opportunity_id text PRIMARY KEY,
  market_key text NOT NULL,
  market_type text,
  instrument_type text NOT NULL DEFAULT 'BINARY',
  duration_seconds integer,
  agent_id text,
  strategy_id text NOT NULL,
  strategy_version text NOT NULL DEFAULT 'v2-live',
  observed_at bigint,
  candidate_at bigint,
  candidate_age_ms bigint,
  candidate_rsi numeric,
  candidate_price numeric,
  direction text,
  entry_mode text,
  decision text,
  accepted boolean NOT NULL DEFAULT false,
  rsi numeric,
  rsi_trajectory text,
  bollinger jsonb,
  band jsonb,
  dmi jsonb,
  adx jsonb,
  structural_trend text,
  short_horizon_direction text,
  projection jsonb,
  expected_cushion numeric,
  cushion_class text,
  order_id text,
  execution_id text,
  effective_stake numeric,
  entry_price numeric,
  entry_noise numeric,
  expiry_at bigint,
  expiry_price numeric,
  result text,
  profit numeric,
  actual_displacement numeric,
  actual_cushion numeric,
  quality_class text,
  settlement_basis text,
  counter_evidence jsonb NOT NULL DEFAULT '[]'::jsonb,
  entry_reason jsonb NOT NULL DEFAULT '[]'::jsonb,
  hard_blocks_checked jsonb NOT NULL DEFAULT '[]'::jsonb,
  evaluations jsonb NOT NULL DEFAULT '[]'::jsonb,
  indicators jsonb NOT NULL DEFAULT '{}'::jsonb,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  revalidation_at bigint,
  submit_at bigint,
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS iq_rsi_opportunities_v2live_market_idx ON iq_rsi_opportunities_v2live(market_key, candidate_at DESC);
CREATE TABLE IF NOT EXISTS iq_rsi_events_v2live (
  id bigserial PRIMARY KEY,
  at timestamptz NOT NULL DEFAULT now(),
  market_key text,
  instrument_type text,
  agent_id text,
  strategy_id text,
  event text NOT NULL,
  decision text,
  reason text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS iq_rsi_events_v2live_at_idx ON iq_rsi_events_v2live(at DESC);
CREATE TABLE IF NOT EXISTS iq_rsi_universe_v2live (
  snapshot_id text NOT NULL,
  market_key text NOT NULL,
  instrument_type text NOT NULL DEFAULT 'BINARY',
  at bigint NOT NULL,
  market_type text,
  canonical text,
  active_id integer,
  enabled boolean,
  availability text,
  payout numeric,
  duration_seconds integer,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  PRIMARY KEY(snapshot_id, market_key, instrument_type)
);
