import { buildMarketSnapshot } from "../relay/consensus/snapshot.mjs";
import { analyzeAtrAgent } from "../relay/agents/atr.agent.mjs";
import { runConsensusAgent } from "../relay/agents/consensus.agent.mjs";
import { analyzeRsiAgent } from "../relay/agents/rsi.agent.mjs";
import { analyzeBollingerAgent } from "../relay/agents/bollinger.agent.mjs";
import { analyzeAdxAgent } from "../relay/agents/adx.agent.mjs";
import { analyzeFibAgent } from "../relay/agents/fib.agent.mjs";
import { analyzeCandleAgent } from "../relay/agents/candle.agent.mjs";
const STEP_MS = 5000; const START_MS = Date.parse("2026-09-20T12:00:00Z"); const base = 1.1; const unit = 0.00008;
const drift = ({ from, count, delta }) => { const out = []; for (let i = 0; i < count; i += 1) out.push(from + delta * (i + 1)); return out; };
const makeCandles = ({ closes, wicks = [] }) => closes.map((close, index) => { const open = index === 0 ? close : closes[index - 1]; const wick = wicks[index] ?? { up: 0, down: 0 }; const bucketEnd = START_MS + (index + 1) * STEP_MS; return { bucketStart: bucketEnd - STEP_MS, bucketEnd, open, high: Math.max(open, close) + (wick.up ?? 0), low: Math.min(open, close) - (wick.down ?? 0), close }; });
const closes = [...drift({ from: base, count: 70, delta: unit * 0.15 })];
const start = closes[closes.length - 1];
for (let i = 0; i < 16; i += 1) closes.push(start + unit * (i + 1) * 1.2);
const peak = closes[closes.length - 1];
closes.push(peak - unit * 0.5, peak - unit * 0.9, peak - unit * 1.3, peak - unit * 1.6);
const wicks = closes.map(() => ({ up: 0, down: 0 }));
wicks[closes.length - 1] = { up: unit * 9, down: 0 };
const candles = makeCandles({ closes, wicks });
const now = candles[candles.length - 1].bucketEnd;
const snapshot = buildMarketSnapshot({ marketKey: "T:OTC", marketType: "OTC", candles, now });
const opinions = { rsi: analyzeRsiAgent(snapshot), bollinger: analyzeBollingerAgent(snapshot), adx: analyzeAdxAgent(snapshot), atr: analyzeAtrAgent(snapshot), fib: analyzeFibAgent(snapshot), candle: analyzeCandleAgent(snapshot) };
console.log("RSI", JSON.stringify({ state: opinions.rsi.state, regime: opinions.rsi.regime, trend: opinions.rsi.priceTrend, min: opinions.rsi.rsiMin, max: opinions.rsi.rsiMax, roll: opinions.rsi.rollingOver, counters: opinions.rsi.counterEvidence.map((c) => c.code) }));
console.log("ADX", JSON.stringify({ regime: opinions.adx.regime, trend: opinions.adx.priceTrend, sep: opinions.adx.diSeparating, rising: opinions.adx.adxRising, sell: opinions.adx.perSide.SELL }));
console.log("ATR", JSON.stringify({ state: opinions.atr.state, climactic: opinions.atr.climactic, volTrend: opinions.atr.volTrend, volRatio: opinions.atr.volRatio, ratio: opinions.atr.ratio }));
console.log("BB", JSON.stringify({ regime: opinions.bollinger.regime, walk: opinions.bollinger.walkSide, bwTrend: opinions.bollinger.bwTrend }));
console.log("CANDLE", JSON.stringify({ structure: opinions.candle.structure, strongTrendAgainst: opinions.candle.strongTrendAgainst }));
const c = runConsensusAgent({ snapshot, opinions, safetyPct: 50 });
console.log("CONSENSO", JSON.stringify({ decision: c.decision, reason: c.reason, vetoes: (c.counterEvidence ?? []).filter((r) => ["RSI_REGIME_CONTRA","RSI_REGIME_CONTRA_FRACA","ADX_DI_CONTRA","ADX_PRECO_CONTRA_TENDENCIA","ATR_EXPANDINDO_CONTRA","CANDLE_CONTRA_TENDENCIA","BOLLINGER_BW_EXPANDINDO_CONTRA"].includes(r.code)).map((r) => r.code), tolerance: c.tolerance }));
